name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git curl

    - name: Install Project Dependencies
      run: |
        chmod +x ./scripts/*.sh
        ./scripts/install_opencv.sh
        ./scripts/install_onnxruntime.sh
        ./scripts/install_zmq.sh
        ./scripts/install_flatbuffers.sh
        ./scripts/install_cppzmq.sh

    - name: Copy Project Files
      run: |
        mkdir project
        cp CMakeLists.txt project/
        cp -R include/ project/include/
        cp -R src/ project/src/
        cp -R tests/ project/tests/
        cp -R fb_schemas/ project/fb_schemas/

    - name: Build the Project
      run: |
        mkdir project/build
        cd project/build
        cmake ..
        make

